#baseURL = "https://magnusson.io/"
baseURL = "https://gunnihinn.github.io"
languageCode = "en-us"
title = "Gunnar Þór Magnússon"
author = "Gunnar Þór Magnússon"
theme = "hugo-flex"
publishDir = "docs"

[security.exec]
allow = [ "^asciidoctor" ]
