baseURL = "https://www.magnusson.io/"
languageCode = "en-us"
title = "Gunnar Þór Magnússon"
author = "Gunnar Þór Magnússon"
theme = "hugo-flex"
publishDir = "docs"

[security.exec]
allow = [ "^asciidoctor" ]
