---
title: Eru moskur ólöglegar á Íslandi
date: 2013-10-18T19:01:05
draft: false
tags: ["Áhugafólk um almenna skynsemi"]
---

Fallegasta orð íslenkrar tungu finnst mér vera "heimska". Það lýsir viðfangsefni sínu svo ótrúlega vel. Að vera heimskur er að hafa sleggjudóma um efni sem maður þekkir ekki og neita að fullnægja grunnforvitni sinni um heiminn. Besta leiðin til að verða svona er að halda sig heima hjá sér, trúa því sem manni er sagt og skoða heiminn ekki sjálfur. Því er þessu ástandi svo vel lýst með "heimsku"; fólk er heimskt því það hangir heima.

Undanfarið hef ég fylgst með hryllingi með umræðu um áætlanir íslenskra múslima að reisa mosku í Reykjavík. Sú umræða hefur einkennst af mikilli heimsku Íslendinga, þar sem menn ausa gífuryrðum yfir fólk sem þeir hafa aldrei hitt eða talað við á grundvelli trúar þess. Ásgeir Ægisson er höfundur nýjasta innleggsins í þessa flórmokun, sem birtist í Morgunblaðinu í dag. Pistill Ásgeirs birtist í heild hér fyrir neðan.

Ásgeir hefur mál sitt svo:

<blockquote>Samkvæmt stjórnarskrá Íslands er trúfrelsi háð því að ekki sé kennt eða framið neitt sem er gagnstætt góðu siðferði eða allsherjarreglu eins og það er orðað. Gott siðferði hlýtur að teljast það að ekki megi hvetja til morða og manndrápa, að ekki megi safna fé til hryðjuverkastarfsemi, að ekki megi ala á fordómum og að ekki megi mismuna fólki eftir kyni, trú, skoðunum, kynhneigð o.s.frv., en allt þetta kenna trúartextar og lögmál íslams. Og sá boðskapur kemur fram í þeim hluta Kóransins sem telst nýjastur og hefur meira vægi en eldri textar sem oft virðast friðsamir við fyrstu sýn</blockquote>

Hér brýtur Ásgeir þá allsherjarreglu sem hann vitnar til, því orð hans eru einmitt fallin til að ala á fordómum á íslamstrúarfólki. Hann heldur því uppi gildum fordómaleysis á sama tíma og hann fellir þau niður. Þetta er einfaldlega http://en.wikipedia.org/wiki/Contradiction[mótsögn]; stundum kallað að misskilja sjálfan sig í daglegu tali.

Á mótsögn má allt byggja og Ásgeir heldur áfram:

<blockquote>Yfirlýst markmið Bræðralags múslima er eyðing Vesturlanda og yfirtaka alls heimsins undir stjórn sharía, eins fáránlegt og það nú hljómar. Margir múslimaklerkar í Mið-Austurlöndum fara ekki leynt með þann boðskap. Slíkur boðskapur og starfsemi flokkast sem landráð samkvæmt íslenskum lögum. [...] Samkvæmt ofangreindu eru íslömsk trúfélög brot á ákvæðum stjórnarskrárinnar og framkvæmdavaldinu er ekki heimilt að samþykkja og skrá félög múslima sem viðurkennd trúfélög og styðja þau með skattaívilnun og styrkjum. Stuðningur sveitarstjórna, eins og nú gerist í Reykjavík, við félagsskap með slíkan boðskap er að sjálfsögðu á móti góðu siðferði og allsherjarreglu.</blockquote>

Í þessari málsgrein fremur Ásgeir harkalega http://en.wikipedia.org/wiki/Fallacy_of_composition[heildarskekkju]. Almennt gengur þessi villa svona:

<ul>
<li>A er satt um X.</li>
<li>X er hluti af hóp Y.</li>
<li>Því er A satt um allt í Y.</li>
</ul>

Hér segir Ásgeir í raun og veru: Sumir sem eru íslamstrúar eru hryðjuverkamenn, því eru allir íslamstrúar hryðjuverkamenn.

Þetta er svo rangt að það tekur því varla að neita því, en fyrst við erum hér er hægt að benda á að það eru til fjölmörg dæmi um hryðjuverkamenn sem eru http://en.wikipedia.org/wiki/Christian_terrorism[kristnir] eða http://en.wikipedia.org/wiki/Jewish_religious_terrorism[gyðingstrúar] en enginn heldur fram að allir kristnir eða gyðingar séu hryðjuverkamenn.

Ég verð að viðurkenna að ég hef lúmskt gaman af þessari næstu hugsun Ásgeirs:

<blockquote>Ég hvet þingmenn Íslendinga til að skoða leiðir og setja lög sem verja málfrelsi fólks á Íslandi á ótvíræðan hátt og að fella úr gildi lög sem setja trú og trúfélög ofar málfrelsi hver svo sem guðsmynd þeirra kann að vera. Trú sem ekki þolir gagnrýni á ekki rétt á sér.</blockquote>

Vill Ásgeir sem sagt fella úr gildi 125. grein almennra hegningarlaga númer http://www.althingi.is/lagas/nuna/1940019.html[19/1940], sem gera kleift að lögsækja almenning fyrir guðlast? Þessum lögum hefur meðal annars http://is.wikipedia.org/wiki/Gu%C3%B0last_%C3%A1_%C3%8Dslandi[verið beitt] að frumkvæði þáverandi biskups Íslands til að rannsaka Spaugstofuna. Sami biskup fékk Sjónvarpið líka til að hætta við sýningu á "Síðasta freisting Krists" eftir Martin Scorsese. Í þessum tilvikum vóg kristin kirkja gróflega að tjáningafrelsi Íslendinga. Vill Ásgeir að jafnt falli yfir alla og að kristin félög verði gerð ólögleg um leið og íslömsk frændsystkini sín?

Ég gæti svo sem fundið meira að "röksemdafærslunum" í pistli Ásgeirs en þar sem hann er hér fyrir neðan ætla ég að leyfa lesendum að gera það sjálfir. Allur pistillinn er móðursjúk hatursræða þar sem staðreyndir um múslima eru afskræmdar og síðustu tíu ára tortryggni í garð allra sem öðruvísi eru er notuð til að espa fólk upp.

Allt sem ég gæti sagt gegn þessum pistli bliknar þó í samanburði við lokaorð hans. Mér er gjörsamlega fyrirmunað að skilja hvað ritstjórn Morgunblaðsins gekk til þegar hún ákvað að birta þetta sorp:

<blockquote>Og við skulum átta okkur á því að íslam kemur ekki frá Guði. Íslam kemur frá villimönnum af eyðimörkum Arabíu. Frumstæð hugmyndafræði með frumstæð gildi: stríð, heiður og hefnd.</blockquote>

------------------

Grein Ásgeirs:


Eru moskur ólöglegar á Íslandi
Ásgeir Ægisson


Þökk sé því fólki sem gaf okkur stjórnarskrána og samþykkti hana árið 1944. Þau hafa líkast til áttað sig á því að ekki er öll trú eins og að til er trú sem hvetur til níðingsverka og lögleiðir kúgun. Samkvæmt stjórnarskrá Íslands er trúfrelsi háð því að ekki sé kennt eða framið neitt sem er gagnstætt góðu siðferði eða allsherjarreglu eins og það er orðað. Gott siðferði hlýtur að teljast það að ekki megi hvetja til morða og manndrápa, að ekki megi safna fé til hryðjuverkastarfsemi, að ekki megi ala á fordómum og að ekki megi mismuna fólki eftir kyni, trú, skoðunum, kynhneigð o.s.frv., en allt þetta kenna trúartextar og lögmál íslams. Og sá boðskapur kemur fram í þeim hluta Kóransins sem telst nýjastur og hefur meira vægi en eldri textar sem oft virðast friðsamir við fyrstu sýn. Þeir sem ekki trúa fullyrðingum mínum ættu nú að taka sig til og lesa 9. kafla Kóransins. Fordómar og ofbeldisáróður sem þar kemur fram skýrir sig fullkomlega sjálfur og þarf ekki að leita nánari útskýringa eða túlkana eins og í öðrum hlutum þeirrar bókar. Fremstu hryðjuverkaleiðtogar múslima vitna enda stöðugt í þann kafla.

Framkvæmdavaldinu á Íslandi er skylt að rannsaka þá starfsemi og boðskap sem fram fer í trúfélögum múslima á Íslandi. Og þar dugar ekki að yfirheyra klerka og spyrja spurninga eða lesa velmeinandi orð á vefsíðum þeirra. Ófrávíkjanleg stefnuskrá íslams er Kóraninn og aðrir trúartextar sem fjalla um Múhameð. Blekkingar til framgangs íslam eru réttlætanlegar í trúartextum íslams. Fyrirmyndin er Múhameð sem beitti lygum og svikum til að komast að andstæðingum sínum og drepa þá. Í moskum á Vesturlöndum hefur starfsemin verið rannsökuð og fram hefur komið að mikill meirihluti klerka stundar ofbeldisáróður og róttæka innrætingu gegn gildum Vesturlandabúa. Yfirlýst markmið Bræðralags múslima er eyðing Vesturlanda og yfirtaka alls heimsins undir stjórn sharía, eins fáránlegt og það nú hljómar. Margir múslimaklerkar í Mið-Austurlöndum fara ekki leynt með þann boðskap. Slíkur boðskapur og starfsemi flokkast sem landráð samkvæmt íslenskum lögum. Eins og annars staðar á Vesturlöndum þurfa lögregluyfirvöld nú að leggja í stöðugt eftirlit með starfsemi moska á Íslandi og halda úti flokkum sem fá það erfiða hlutverk að lokka fram þá múslima sem leggja í jihad, en jihad er heilög skylda hvers múslima. Og allt á kostnað skattborgaranna. Samkvæmt ofangreindu eru íslömsk trúfélög brot á ákvæðum stjórnarskrárinnar og framkvæmdavaldinu er ekki heimilt að samþykkja og skrá félög múslima sem viðurkennd trúfélög og styðja þau með skattaívilnun og styrkjum. Stuðningur sveitarstjórna, eins og nú gerist í Reykjavík, við félagsskap með slíkan boðskap er að sjálfsögðu á móti góðu siðferði og allsherjarreglu. Að sjálfsögðu er ekki hægt að banna einstaklingum að aðhyllast sína trú eða sannfæringu (enda andstætt stjórnarskrá Íslands), en þannig félagsskapur verður einfaldlega að starfa utan skráðra félaga. Þó er heimilt að leysa upp slíkan félagsskap ef hann telst ólöglegur eða gerist brotlegur.

Atburðarásin í borgarstjórn Reykjavíkur er með ólíkindum. Borgarfulltrúar vilja refsa yfirvöldum í Rússlandi fyrir að setja lög um fræðsluefni til barna um samkynhneigð. Á sama tíma styðja þau félagsskap sem boðar hugmyndafræði þar sem samkynhneigðir skulu pyntaðir og drepnir. Moska verður tákn Reykjavíkur. Óvinatákn vestrænnar menningar og kristinna gilda sem hún byggir á. Vinstri menn fagna og sjálfstæðismenn samþykkja með þögninni. Bræðralag múslima og dótturfélög þeirra heyja nú áróðursstríð á Vesturlöndum. Hluti af þeirri baráttu felst í því að byggja moskur og koma þar inn klerkum. Frá 11. september 2001 hefur mikill fjöldi moska verið byggður á Vesturlöndum. Fjármagnið kemur frá Sádi-Arabíu og Bræðralagið útvegar klerka og fræðsluefni. Hlutverk klerkanna er að hafa áhrif á stjórnvöld og fjölmiðla á hverjum stað og stjórna umræðu og kennsluefni um íslam. Innræting barna múslima er einnig á þeirra könnu og börn múslima eru tekin í kórannám í moskum, oft frá 5 ára aldri. Félög múslima á Vesturlöndum hafa á síðustu árum gengið hart fram í að þagga niður í þeim sem segja sannleikann um íslam og Múhameð. Þar er öllum ráðum beitt. Hótanir, ofbeldi, morð, hryðjuverk og lögsóknir eru þar á meðal. Lögsóknir hafa farið fram með stuðningi arabískra auðmanna þar sem gagnrýnendur íslams eru ákærðir og lögsóttir fyrir brot á lögum um málfrelsi, trúfrelsi, kynþáttaníð eða guðlast. Búast má við slíkum árásum á einstaklinga á Íslandi ef íslam fær að dafna hér. Ég hvet þingmenn Íslendinga til að skoða leiðir og setja lög sem verja málfrelsi fólks á Íslandi á ótvíræðan hátt og að fella úr gildi lög sem setja trú og trúfélög ofar málfrelsi hver svo sem guðsmynd þeirra kann að vera. Trú sem ekki þolir gagnrýni á ekki rétt á sér. Og við skulum átta okkur á því að íslam kemur ekki frá Guði. Íslam kemur frá villimönnum af eyðimörkum Arabíu. Frumstæð hugmyndafræði með frumstæð gildi: stríð, heiður og hefnd.