---
title: Sko Svía
date: 2013-10-30T19:56:21
draft: false
tags: ["Áhugafólk um almenna skynsemi"]
---

Síðan ég byrjaði að lesa leiðara Morgunblaðsins hefur mig langað að skoða einhvern þeirra betur hér. Það er ekki vandkvæðalaust, því leiðararnir skiptast í tvo flokka. Í öðrum er talað af rósemi og skoðanir viðraðar með vísun í rök og ég hef ekkert út á þá leiðara að setja. Í hinum fara höfundar eins og kettir í kringum heitan graut, nefna fá ef einhver nöfn eða hugmyndir og skjóta ómerkilega á allt í færi. Þó mér þætti gaman að skoða þessa leiðara betur er það ekki oft hægt, því í þeim eiga höfundarnir til að segja ekki nokkurn skapaðan hlut. Mig er farið að gruna að ritstjórarnir skiptist á að skrifa leiðara blaðsins og að markmiðin með skrifum þeirra séu ansi ólík.

Í dag stíga höfundar seinni tegundar leiðaranna nógu nærri raunverulegum staðhæfingum til að hægt sé að meta orð þeirra af eigin verðleikum. Efni leiðarans eru áhyggjur Ernu Solberg, forsætisráðherra Noregs, af fréttum ríkisútvarps Noregs um að sænsk yfirvöld hafi lagalega heimild til að hlera tölvupóstsamskipti Norðmanna því stór hluti þeirra fari gegnum Svíþjóð. Leiðarahöfundar stökkva á orð Ernu um að ef fullnægjandi útskýringar á málinu fáist ekki munu Norðmenn "fara með málið lengra":

[quote]
----
Ekki var tekið fram hvert norski forsætisráðherrann ætlaði með málið. Varla í suðurátt, því þar ná menn ekki upp í nefið á sér vegna hlerana og treysta sér því varla til að vera með nefið niðri í annarra manna hlerunum, þótt þær séu jafnspennandi og hleranir Svía á Norðmönnum hljóta að vera.

Ekki geta þeir farið með málið lengra í austur, því þá lenda þeir í Svíþjóð og fari þeir enn austar, á sléttur Rússlands, er alls ekki víst að Pútín sé sömu megin og Norðmenn, það er að segja í hópi hinna hleruðu, en ekki í hinum hópnum með tól á eyrum.
----

Allir leiðarar af seinni tegundinni eru í þessum stíl, þar sem útúrsnúningar, einfeldningsháttur og uppnefningar liggja í einum graut. Halda leiðarahöfundar til dæmis í alvöru að ríkisstjórnir Frakklands og Þýskalands, sem eru væntanlega þeir sem ná ekki upp í nefið á sér, geti ekki veitt tveim hlutum athygli í einu? Aðeins lengra vísa höfundar afskiptum Evrópusambandsins af málinu á bug með að uppnefna starfsfólk þess "æðstustrumpana í Brussel", eins og er reglulega gert í þessum leiðurum. Á meðan mér finnist alveg jafn skemmtilegt að uppnefna fólk og leiðarahöfundum verð ég að benda á að fyndin uppnefni eru ekki rök fyrir einu né neinu.

Ég veit ekki alveg hvernig ég eigi að flokka þessar málsgreinar. Með góðum vilja og víðri skilgreiningu á rökum er hægt að segja að leiðarahöfundar færi hér rök fyrir að Norðmenn geti ekki vænt aðstoðar frá löndum í austri, suðri eða vestri (Bandaríkin eru afgreidd af sama háðstóni í annari málsgrein). Þá dettur mér helst í hug að frávísanir höfunda hér séu öll dæmi um að http://en.wikipedia.org/wiki/Non_sequitur_(logic)[niðurstaða tengist staðhæfingum ekki beint]. Áhugasamir lesendur geta rýnt betur í http://en.wikipedia.org/wiki/List_of_fallacies[þennan rökvillulista] og séð hvort þeir finni þessum staðhæfingum betra heimili.

Höfundar ráðleggja að lokum Norðmönnum að leita til okkar Íslendinga í norðri með vandræði sín (Ísland liggur reyndar til vesturs frá Noregi). Hér virðast þeir nálgast eitthvað sem þeir hafa áhuga á að tala um, sem tengist ásökunum um að sími Jóns Baldvins Hannibaldssonar hafi verið hleraður þegar hann var hann var utanríkisráðherra:

[quote]
----
Árni Páll Árnason, sem verið hafði pólitískur lærlingur í utanríkisráðuneytinu á umræddum tíma, sá þarna færi og komst í viðtal á "RÚV", sem stofnunin virtist taka í fullri alvöru, um að lærlingssíminn hans hefði líka verið hleraður á sama tíma. Ekki var upplýst hvort lærlingshlerarinn hefði haft sérstakan koll fyrir sig.

En það breytti ekki því, að 15 mínútna frægðin sem Árni Páll Árnason fékk hjá "RÚV" út á hina meintu hlerun, sem hlýtur þá að hafa verið gerð af manni sem fór númeravillt, dugði honum í yfirstandandi prófkjörsbaráttu!
----

Reyndar kasta höfundar nokkrum steinum í mótmælendur framkvæmda í Gálgahrauni og Jón Baldvin áður en þeir komast að Árna Páli. Hér finnst mér athyglisverðust fullyrðing höfunda um að Árni hafi komið vel úr prófkjöri því hann hafi sagt að sími sinn hafi einnig verið hleraður. Ég veit ekkert um það, frekar en meintar hleranir á Jóni Baldvini, en finnst líklegt að ýmsir aðrir þættir (eins og kosningabarátta Árna Páls) hafi vegið þyngra til velgengni hans. Höfundar segja hér að vegna þess að atburður B hafi gerst á eftir atburði A þá sé A orsök B. Þetta er mjög vel upp alin rökvilla sem heitir http://en.wikipedia.org/wiki/Post_hoc_ergo_propter_hoc[post hoc ergo propter hoc] á latínu. Hana má finna við hin ýmsu tilefni, allt frá léttvægum (ég fór í lukkuskóna mína svo það ringdi ekki) til háalvarlegra málefna (ég bólusetti barnið mitt svo það varð einhverft), en öll þeirra eiga sameiginlegt að vera ógildar rökfræðilegar hreyfingar.

Þessi fullyrðing höfunda um Árna Pál er þó eins og flest annað í þessari tegund leiðara Morgunblaðsins; máttlaust og illkvitnilegt skot sem breiðir yfir innihaldsleysi leiðarans sjálfs. Ef einhverja hugmynd má grafa úr rústum þessa orða er það helst að pistlahöfundum þyki léttvæglegt og lítt alvarlegt mál að samskipti fólks, hvort sem það er almennings eða stjórnmálamanna, séu hleruð og réttur þess til einkalífs því troðinn fótum. Þar sem sú tilfinning er í beinni mótsögn við annan nýlegan, öllu skynsamari, leiðara Morgunblaðsins hlýtur aðeins annar ritsjóri þess að vera þessarar skoðunar. Megi honum ganga vel að lifa með henni.


[quote]
----
Sko Svía
Ritstjórn Morgunblaðsins (Davíð Oddson og Haraldur Johannessen)

Veður hafa minnt á að vetur er genginn í garð víðar en hér og fóru þau mikinn í Englandi, Danmörku og Svíþjóð um helgina með tilheyrandi búsifjum fyrir þarlenda. Reynsla og líkur standa til þess að við munum fá okkar skammt, þótt tíminn sé óviss. Ekki þó vegna þess að veður séu smitandi og lúti lögmálum pestanna. En hleranir virðast á hinn bóginn vera það.

Hleranafárviðrið hefur skekið meginland Evrópu síðustu vikur og nú hefur það óvænt náð norður á dauðhreinsuð svæði Skandinavíu. Þannig var upplýst á vef Mbl. í gær, að ríkisútvarp þeirra í Noregi hefði greint frá því "að samkvæmt sænskum lögum geta þarlend stjórnvöld haft eftirlit með tölvupóstssamskiptum og netumferð í Noregi, en hún fer að stórum hluta í gegnum Svíþjóð.

Erna Solberg, forsætisráðherra Noregs, hefur nú krafið starfsbróður sinn í Svíþjóð, Fredrik Reinfeldt, um skýringar.

"Við ræddum um þetta í gær, og ég sagði að við vildum fá nánari upplýsingar," segir Solberg í samtali við NRK.

"Við höfum áhyggjur af því að stór hluti netumferðarinnar okkar fer í gegnum Svíþjóð. Þar af leiðandi sagði ég við Reinfeldt að við myndum fara með málið lengra," sagði norski forsætisráðherrann aðspurður".

Ekki var tekið fram hvert norski forsætisráðherrann ætlaði með málið. Varla í suðurátt, því þar ná menn ekki upp í nefið á sér vegna hlerana og treysta sér því varla til að vera með nefið niðri í annarra manna hlerunum, þótt þær séu jafnspennandi og hleranir Svía á Norðmönnum hljóta að vera.

Ekki geta þeir farið með málið lengra í austur, því þá lenda þeir í Svíþjóð og fari þeir enn austar, á sléttur Rússlands, er alls ekki víst að Pútín sé sömu megin og Norðmenn, það er að segja í hópi hinna hleruðu, en ekki í hinum hópnum með tól á eyrum.

Auðvitað gætu Norðmenn reynt að halda með málið lengra og þá í vesturátt. Þeir hljóta að eiga hauk í horni þar sem Obama er eftir friðarverðlaunin sem hann fékk fyrir að vinna bandarískar kosningar. Obama mun hafa látið segja sér þrem sinnum að þetta væri ekki aprílgabb og hafi ekki sannfærst að fullu fyrr en hann var upplýstur um að hleranir á norsku nóbelsnefndinni staðfestu þessar fréttir. Verðlaunaveitingin til Obama var að auki jafnvel ekki eins fáránleg og þegar gleðipinnarnir í Jagland-nefndinni ákváðu að veita æðstustrumpunum í Brussel friðarverðlaun vegna þeirrar birtu sem eldar og atvinnuleysi í Grikklandi og Spáni brugðu á álfuna. En það er þó ekki víst að Obama forseti sé sérstaklega upplagður til að gefa góð ráð til vina sinna í hlerunarmálum einmitt núna, þótt hann sé fús til að hlusta á Norðmenn svo lítið beri á.

Og ef þetta er staðan þá er augljóst að Norðmenn ná engri annarri átt en að halda í norður, ef Erna Solberg forsætisráðherra er ákveðin í að "fara með málið lengra".

Sem betur fer mun norski forsætisráðherrann ekki koma að tómum kofunum hjá frændum sínum, kóngaskáldunum. Í útvarpsfréttum í gær var þannig alllangur pistill um að talsmenn "hraunavina" vildu að lögreglan kannaði hvort hún sjálf hefði verið að hlera hraunavini. Talsmaðurinn tók fram að hann vissi ekki til að nokkur skapaður hlutur benti til slíkra hlerana á símum tveggja forystumanna hraunavina en sjálfsagt væri að lögreglan stæði fyrir máli sínu. Þetta var ekki verri nálgun á hlerunarmáli en þegar ógnvænlegur stormur og manndrápsveður urðu í tebollanum á fréttastofu "RÚV" vegna fullyrðinga um að sími Jóns Baldvins Hannibalssonar hafi verið hleraður fyrir einum 15 árum eða svo af manni sem annar maður hefði séð sitja á kolli í Landssímahúsinu.

Árni Páll Árnason, sem verið hafði pólitískur lærlingur í utanríkisráðuneytinu á umræddum tíma, sá þarna færi og komst í viðtal á "RÚV", sem stofnunin virtist taka í fullri alvöru, um að lærlingssíminn hans hefði líka verið hleraður á sama tíma. Ekki var upplýst hvort lærlingshlerarinn hefði haft sérstakan koll fyrir sig.

Auðvitað var þetta mikil hneisa fyrir þá tugi metnaðarfullra starfsmanna utanríkisráðuneytisins sem skipuðu stöðurnar sem lágu á milli ráðherrans og lærlingsins og enginn virtist nenna að hlera. En það breytti ekki því, að 15 mínútna frægðin sem Árni Páll Árnason fékk hjá "RÚV" út á hina meintu hlerun, sem hlýtur þá að hafa verið gerð af manni sem fór númeravillt, dugði honum í yfirstandandi prófkjörsbaráttu!

Á Íslandi er því kjörlendi fyrir þá sem vilja kafa ofan í hlerunarmál og vilji Solberg fara með sitt hlerunarmál lengra þarf hún ekki að leita annað.
----
